### ISSUE TITLE
Bug: Missing blank line before auto-complete text ctrl array

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1006]
### Description:

When adding an auto-complete array to a text control, the opening brace for the wxArrayString does not start with a blank line -- instead it is added to the end of the previous line. For an example, add a hint to a text control, then an auto-complete array.

**Comment by Randalphwa** [comment]
This requires another setting before it reproduces -- e.g., add a hint, and then the bug appears.
