### ISSUE TITLE
Bug: for wxFrame, wxDialog and wxPopupTransientWindow forms without a style defined, the const style value is wrongly generated

### ISSUE THREAD

**Issue by hobbitdev** [KeyWorksRW/wxUiEditor#1020]
### Description:

wxUIEditor v1.1.1 (beta)

For wxFrame, wxDialog and wxPopupTransientWindow forms without a style defined, the const style value is wrongly generated; perhaps even wxPanel is affected.
Instead of `const int form_style = ;` it should be `const int form_style = 0;`

As I see it, even the following code in class constructor seems wrong.
`long style = wxDEFAULT_DIALOG_STYLE` should by `long style = 0`

example for wxDialog
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/3daf7aea-db5b-419d-a303-333bc7f0438b)

**Comment by KeyWorksRW** [comment]
This affects all properties that use a string for their value -- it is possible that the string will be empty, and if that is used as the value to assign, then the code generation is wrong. For each of the string properties that have a possible const_value, a check for an empty string must be made and an appropriate assignment made if it's empty. See `BaseCodeGenerator::GenerateClassHeader()`.

**Comment by KeyWorksRW** [comment]
This affects all properties that use a string for their value -- it is possible that the string will be empty, and if that is used as the value to assign, then the code generation is wrong. For each of the string properties that have a possible const_value, a check for an empty string must be made and an appropriate assignment made if it's empty.
