### ISSUE TITLE
Only allow single Image List per project

### ISSUE THREAD

**Issue by Randalphwa** [KeyWorksRW/wxUiEditor#1034]
### Description:

This issue is related to #1023 and the current work being done on gen_Images.

## Problems

The initial implementation of the Images list was designed to allow the dev to have a single file generated that contained all embedded images and the functions that could retrieve them. However, it required the dev to add every image to this list. That's okay for a small project or one with few images, but was a pain for situations like wxUiEditor itself which has almost 200 images.

I currently have a branch with an implementation of auto_update referred to in #1023. That works fine for adding images -- i.e., if it's turned on it will immediately collect all the images from all the controls/forms in the project. From that point on, if the dev adds an image to a control, it will be automatically added to the Images list. However, what it doesn't do is remove an image if the user changes or eliminates an image from a control or form.

This problem is going to get worse if I add support for an Images list within a folder. If that's added _after_ an Images list is added to the project, then all the images added to the folder's Image list need to be removed from the Project's image list.

The worst-case scenario is if the dev adds an Image list to the project, does _not_ check auto-update choosing instead to manually add some images to the list. Then another dev adds an Image list to a Folder they are working in and sets that to auto_update. The auto_update picks up some images from the folder that also exist in the project's Image list. When the two files are generated, you have duplicate images and you can no longer link the executable.

An additional problem scenario is if an image is used in a control in a folder, and is also used in a control outside of the folder. In that case, the project's Image list needs to take precedence, but that means adding the project's Image list header file to the form in the folder that has that image along with the header file from the Folder's image list file. That rather defeats the purpose of having a folder Image list since you still have to include _both_ header files.

This would work with C++17 or later since adding `inline` would prevent duplication. However, it's too recent a standard to require it (even wxWidgets 3.3 has only bumped the minimum standard to C++14).

## Proposed Solution

- Only allow one Image List per project
- Change the terminology to "Image List" instead of "Image Form" since there can only be one
- Always place the Image List (if there is one) as the first child of the project
- Old projects will have auto_update unchecked when read, but the default setting is checked
- Description for auto_update must indicate that all unused images will be removed from the list

### Auto_update checked changes

The following are the changes that will occur if auto_update is checked

- _Only_ images actually used in the project will be in the list
- The tool for manually adding an image will either be disabled, or will display a message box indicating why it cannot be used
- The list will always be sorted
- If an image is added to a form or control, it will automatically be added to the Image List
- If an image is removed or renamed in a form or control, and the image is not in use by another form or control, it will be removed from the Image List
- Items in the list cannot be moved either via dragging or keyboard commands

**Comment by KeyWorksRW** [comment]
This was fixed in PR #1038
