### ISSUE TITLE
Add tt_string::make_wxString()

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1035]
### Description:

When building wxUiEditor for Windows, passing `wxString::wx_str()` to a function that expects `const std::string&` will fail with wxWindows 3.2.x, and succeeed with wxWindows 3.3.x. Calling `wxString::utf8_string()` instead works fine for either version (and is efficient on wxWidgets 3.3.x where no conversion needs to be done).

tt_string also has a `wx_str()` function which effectively works in reverse by converting the string to UTF16 if compiled on WIN32 without wxUSE_UNICODE_UTF8 defined. However, I'm finding that a bit confusing, particularly since using `wxString::wx_str()` when building with wxWidgets 3.3 works fine, and then the build fails on GitHub which is building with wxWidgets 3.2.

`tt_string::wx_str()` returns either std::wstring or std::string, but often what we really need is a `wxString`. Creating a function like `wxString make_wxString()` seems both more useful and more understandable then the current `wx_str()`.

**Comment by Randalphwa** [comment]
While we're doing this, it would make sense to also look at all calls to wxString::wx_str() and tt_wxString::wx_str() and in most cases change that to utf8_string(), particularly when converting filenames for use with pugi_xml or anything else that expects a utf8 string.
