### ISSUE TITLE
Add a Documention panel that uses wxWebView

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1096]
### Description:

Currently, all the Help URLs for wxWidgets, wxPython and wxRuby utilize whatever the default browser is. While that works, it also creates a new browser window every time. An alternative to this would be to create a wxWebView panel, similar to the way we have a Mockup panel. It would of course need a toolbar with the traditional home, back and forward buttons. It could also have language buttons so that a user could easily switch between the documentation of a widget between C++, Python and Ruby.

**Comment by Randalphwa** [comment]
The Docs panel is working for C++, Python and Ruby. There are some possible features that could be added, but I think those can wait for a future release and can have their own issue.
