### ISSUE TITLE
Generated C++ non-derived class header files should use class forward definitions for members

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1110]
### Description:

A lot of the `wx/` header files we add to a generated class header file could be replaced with a class forward definition. For example, we might have a class:

```C++
#include <wx/toolbar.h>

class ... : public wxDialog
{
    wxToolBar* m_toolBar;
};
```

That means any module that needs to invoke the dialog will make the compiler read the `wx/toolbar.h` file just to find out that `wxToolBar*` is a class pointer. A more efficient way would be:

```C++
class wxToolBar;  // #include <wx/toolbar.h>

class ... : public wxDialog
{
    wxToolBar* m_toolBar;
};
```

This saves the compiler from having to read header files that is doesn't actually need, slightly speeding up the compiler as a result.

Unfortunately we can't make this the default unless it is a non-derived class. At the very least, we should use class forward definitions for class members in _all_ non-derived classes, since the header file(s) needed for the src file will already be generated.

If we _do_ decide to make this an option, then it might make sense to create a C++ Header Settings category and move all the header-specific properties into that category. We already have 12 properties under C++ Settings, so we may need to do this anyway.

**Comment by Randalphwa** [comment]
It's a great idea, but _very_ involved to implement correctly. I tried it on wxUiEditor and it missed event handler references and duplicated the forward class when different header files needed the class and ended up with one class source file missing the header file. It would be a _lot_ of work to try to find all the cases where you can't use class forwarding -- and even then, if I miss one a user could end up with non-compilable code. It's just not worth it... 😞
