### ISSUE TITLE
Add support for conversion functions to bitmaps

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/wxUiEditor#113]
### Description:

**wxImage** has four conversion functions which could potentially be useful. For example, **ConvertToGreyscale()** could be useful to use for the unchecked image in a menu. **ConvertAlphaToMask()** would be useful for a PNG Header image being used for a toolbar button.

We could add a `conversion` option that would have:

    - none
    - disabled
    - greyscale

This could be saved as an integer with 0 being none, and the others in numerical order.

The alpha conversion should only be available for PNG Header images, so it would need to be it's own option. We could store it as a bit flag added to the above conversion integer so that an extra parameter wouldn't be needed. Note that code generation would be quite different since unlike the other conversions, this one does not return a wxImage.

**Comment by KeyWorksRW** [comment]
Need to at least investigate this further for the 1.1 release since it would involve an additional property and affect code generation for all 4 languages.

**Comment by KeyWorksRW** [comment]
Postponing to 1.1.x milestone -- there isn't time to work on this until after the 1.1 release.

**Comment by Randalphwa** [comment]
Low priority, so I removed all milestones for this issue.

**Comment by KeyWorksRW** [comment]
I just don't think this is going to be used enough to justify further expanding the bitmaps properties -- they are already long, and about to get a fourth parameter.
