### ISSUE TITLE
Bug: The option useful to import DialogBlocks projects disappeared

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1134]
### Description:

I'm using the latest version 1.1.2

In a previous version (it was v1.1.1) there was the following option useful to import DialogBLocks projects saved as XML, but now it is disappeared.

![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/9fc0a659-9858-41c5-80da-708707637e1c)

**Comment by KeyWorksRW** [comment]
That's temporary -- there's still a *lot* of parts of it that I don't
import yet. I pulled it from the 1.1.2 release but I'm fully expecting to
finish it up before the 1.1.3 beta release.

**Comment by hobbitdev** [comment]
OK, got it ... thank you.
As soon as you are ready with something stable, I could help you importing some projects of mine in order to debug that feature.

**Comment by KeyWorksRW** [comment]
I still don't handle any font properties, nor can I convert wxContextHelpButton and wxPropertySheetDialog. Aside from that, I believe it's now in fairly good shape -- so feel free to test on any daily build from 8/15 onwards.

**Comment by KeyWorksRW** [comment]
I believe wxContextHelpButton is the only thing left that isn't supported. Unless I add support for the control to wxUiEditor, there isn't going to be a way to convert it. I'm leaving the issue open until I decide whether or not to add a wxContextHelpButton control to wxUiEditor.

**Comment by rossanoparis** [comment]
Personally I never used such control, however it is part of wx library, I think it should be present in a RAD tool for those who could need it.

**Comment by KeyWorksRW** [comment]
Issue #1339 added to implement wxContextHelpButton and then import it from DialogBlocks. Closing this issue since the remaining problem now has it's own issue.
