### ISSUE TITLE
Add wxValidator support to Python and Ruby

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1135]
### Description:

Both Python and Ruby support all 4 validator types. Currently, we only generate code for C++ validators. See BaseCodeGenerator::GenSettings in gen_construction.cpp

**Comment by Randalphwa** [comment]
wxPython supports a user-created custom validator, but none of the standard wxWidgets validators.

wxRuby supports a Wx::TextValidator that can be used to validate styles as well as limit allowable characters. However, it does not provide any of the Transfer functions.

I'm going to add the code necessary for languages besides C++ to GenValidatorSettings() in gen_common.cpp, but for now, this function will only be called when generating for C++.
