### ISSUE TITLE
Add optional enable attribute to XML generator classes

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1159]
### Description:

It would be helpful to support an optional `enabled=` attribute to the xml `gen class` node. If specified, the value would be either internal or debug. If "internal" was set, then the entire generator would be ignored if INTERNAL_TESTING was not set. If "debug" was set, then the entire generator would be ignored if _DEBUG was not set.

This would be primarily useful for interfaces, though it could also be useful for experimental generators such as "DocViewApp".

**Comment by Randalphwa** [comment]
I'm just going to go with "internal" for now and skip "debug". Presumably the classes or interfaces are experimental, so the _only_ time they should not be shown is a non-internal release build. We shouldn't need the additional granularity of a debug-only class or interface.
