### ISSUE TITLE
Bug: Using wxWrapSizer will generate invalid code for wxRuby

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1186]
### Description:

Currently, **wxRuby** doesn't support **wxWrapSizer**. Unless the sizer is added before wxRuby's release, we are going to need to replace it with a different sizer for the generated code to still work.

**Comment by KeyWorksRW** [comment]
See https://github.com/mcorino/wxRuby3/issues/148

**Comment by Randalphwa** [comment]
0.9.0 fixes this, verified in sdi_test.
