### ISSUE TITLE
Add Node checking function to fix potential wxWidgets assertions

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1187]
### Description:

I've run into both **DialogBlocks** and **wxFormBuilder** projects that are imported and result in **wxWidgets** assertions when Mockup displays form(s) in a Debug build. Presumably, the generated code will also result in code that asserts when run under Debug builds.

For importing only, I think should have an additional function that takes a Node* pointer and walks the tree fixing any settings that would result in **wxWidgets** assertions. This could then be run when importing, appending or pasting from another project.

**Comment by Randalphwa** [comment]
This is now in place, and handles the most common importing issues (alignment, invalid row setting in wxGrid-type sizers). Additions to it will be on a case-by-case basis, so closing this as completed.
