### ISSUE TITLE
Bug: Menu Item and Toolbar Tool not allowed to have same ID

### ISSUE THREAD

**Issue by Jofagi** [KeyWorksRW/wxUiEditor#1231]
### Description: 
I'm new to wxUiEditor and wxWidgets in general, so maybe this is not a bug but lack of understanding on my side.

- I'm using wxUiEditor for generating C++ base class code.
- I've got a wxMenuBar containing a wxMenu and it contains a wxMenuItem.
- I've also got a wxToolBar to containing a tool that corresponds to the menu item.
- Example: (renamed to .txt so I'm allowed to upload)  [mre.wxui.txt](https://github.com/KeyWorksRW/wxUiEditor/files/12813598/mre.wxui.txt)

My idea is that either clicking the tool or selecting the menu entry shall do the exact same thing. This means to me, both should have the same ID. As far as I understand, this is well supported by wxWidgets. `wxEVT_TOOL` is even an alias of `wxEVT_MENU`.

#### Action:
Try to change the tool's ID from `MY_DEMO_ACTION2` to the menu item's ID `MY_DEMO_ACTION`.

#### Behavior:
wxUiEditor gives me the "Property Error" message "You have already used this ID for another control. Please choose a different ID.".

#### Expected Behavior:
It should let me assign the same ID to the menu and tool.

#### Workaround:
I can edit the .wxui file directly so both controls have the same ID. The generated C++ is as I want it: 
```cpp

// Header
enum
{
    MY_DEMO_ACTION = wxID_HIGHEST + 1
};

// Source
bool MyFrameBase::Create(/*...*/)
{
    // ...
    m_toolBar-AddTool(MY_DEMO_ACTION, /*...*/);
    // ...
    auto* menu_item = new wxMenuUtem(/*...*/, MY_DEMO_ACTION, /*...*/);
    // ...
}
```

**Comment by KeyWorksRW** [comment]
That's definitely a bug -- as you noted it's perfectly fine to share an id between a menu item and a toolbar.
