### ISSUE TITLE
Bug: Custom controls from DialogBLocks are not imported

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1232]
### Description:

wxUIVersion: v1.1.3 (night build 08/10/2023)

I'm testing the import feature from DialogBLocks XML projects with this file: [Test-03.zip](https://github.com/KeyWorksRW/wxUiEditor/files/12841057/Test-03.zip)
Custom controls are not imported, wxUIEditor shows the following message
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/150bf095-003d-4fcd-aa2e-5f6966e92995)

**Custom parameters**
Often, custom controls have got their own parameters, they must be imported too

- DB "Custom arguments"
`Parameter1, Parameter2, %PARENT%, %ID%, %POSITION%, %SIZE%, %STYLE%`

- wxUI "parameters"
`(Parameter1, Parameter2, this, ${id}, ${pos}, ${size}, ${window_style})`

**Custom control layout**
Even the size declared for a custom control should be respected, I mean its occupied area, otherwise the entire window layout can't be appreciated.

Here, as it is appear in DB
(I would expect to see the same in wxUIEditor)
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/b0f1e0df-7ef0-4c83-b6ad-a4ea3b43a125)

**Comment by Randalphwa** [comment]
PR #1235 supports importing everything in your project, including the various parameter macros. It should appear in the 10/10 daily build. I'm going to work on the Mockup display as a separate commit, since that's a bug affecting all Custom Controls that have a size specified.

**Comment by KeyWorksRW** [comment]
Custom controls now have a custom_mockup property that lets the user set the expected size so that it will be displayed correctly in the Mockup Panel, and importing custom controls has been fixed. I'm marking this as closed accordingly. Please re-open if I missed something...
