### ISSUE TITLE
Bug:  Importing from other projects such as DialogBlocks or wxFormBuilder, for wxDialog forms the general font property is not imported.

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1258]
### Description:

wxUiEditor version: latest nigth build

I discovered that for wxDialog the user is not allowed to set a font as global font for the entire window. This force the user to set for each control on it the same font as many times as the number of controls on the window.

What's the meaning of it?

Instead, I think it is usefull to set a global font for the entire window, then if I need to specify something different for a specific control I set only for that control a different font.

I reckon this kind of behaviours related to window's properties which are potentially inherited from its controls should be extended for all properties like the font one.

**Comment by KeyWorksRW** [comment]
I took out the font option a long time ago, probably because I was too well trained by UI Designers to _never_ use a non-standard font for an entire dialog. Nevertheless, it's not the job of wxUiEditor to enforce UI decisions any more than wxWidgets itself does. So as long as the window property actually works for the specific form, then wxUiEditor should support it.

**Comment by rossanoparis** [comment]
I totally agree with you, and I could add that a good RAD tool should be versitile and offers resonable options to the user; than is up to the user which is the best way to design the UI depending of specific needs.

**Comment by Randalphwa** [comment]
I just checked in a commit that adds font and foreground color properties to dialogs. Importing and code generation were already in place, so the only thing missing was the actual properties.

Note that the Mockup panel does _not_ display changes to font or color properties. The code for the Mockup panel was written 3 years ago, and really needs an extensive review to see if I can't come up with something that more accurately displays what a dialog and frame window would look like. With the current plan to release 1.2 in two weeks, I'm not going to tackle that now...

**Comment by KeyWorksRW** [comment]
The Mockup overhaul is covered by #1275 so closing this issue as fixed.
