### ISSUE TITLE
Bug:  in a window form with two-steps window creation is inherited, the generated code is created with a wrong call chain to ::Create() function

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1267]
### Description:

wxUIEditor version: latest daily build

This window is inherited from `wxhKeyboardBase`, which is, of course, a wxDialog too
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/07e311bb-182e-4501-a467-3792bc7bb029)

The generated code is wrong
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/ffb91905-d42d-4886-b49b-2ca785f77c4d)

It should be like this instead
(code generation should use `wxhKeyboardBase` not `wxDialog`)
```
if (!wxhKeyboardBase::Create(parent, id, title, pos, size, style, name))
    return false;
```

Generally speaking this is not the right way to call the Create() function for inherited two-steps forms.
This kind of behaviour results in a blocking bug for projects imported from other RAD tools.
Of course a kind of workaround code could be written to solve it, but I hope you could take in consideration to modify the code generation for all windows where two-steps creation is allowed.

**Comment by rossanoparis** [comment]
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/6d2c3fbe-8623-470f-9325-cdd639487930)
Excuse me, I beg your pardon, I don't want to press you at all, but I'd like to know if you could take in consideration this issue as it is blocking for imported projects ...
Thank you very much

**Comment by KeyWorksRW** [comment]
Dropping priority and milestone since the PR should fix the import from wxFormBuilder as well as any new C++ projects that use a derived class. Still need to fix Python and Ruby, but that will be a lot more involved to verify the fix.

**Comment by rossanoparis** [comment]
Realy many thanks for that :)

With this issue solved plus [this one](https://github.com/KeyWorksRW/wxUiEditor/issues/1282) I will be able to finalize my porting from wxFB projects

**Comment by KeyWorksRW** [comment]
The Ruby code generation doesn't use 2-step construction.

The Python code generation does, but initialization from an inherited class is completely different from C++ so right off hand, I don't think it applies.

In any event, these two languages are quite different from C++ in how a form gets created. If a change to code generation needs to be made for them to better support inheritance, then they should have their own issues.
