### ISSUE TITLE
Bug: "generate_const_values" property doesn't generate useful code for its porpouse

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1271]
### Description:

If I'm not wrong, the code generated by using "generate_const_values" property seams not be usefull.
Here an axample.
```
class CMainFrameDesigner : public wxFrame
{
public:
    const int form_id = ID_CMAINFRAME;
    const int form_style = wxDEFAULT_FRAME_STYLE;
    const wxPoint form_pos = wxDefaultPosition;
    const wxSize form_size = wxSize(800, 600);
    static const wxString form_title() { return wxString::FromUTF8("CMainFrameDesigner"); }

    CMainFrameDesigner() {}
    CMainFrameDesigner(wxWindow* parent, wxWindowID id = ID_CMAINFRAME, const wxString& title =
        _("CMainFrameDesigner"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800, 600),
        long style = wxDEFAULT_FRAME_STYLE|0, const wxString &name = wxFrameNameStr)
    {
        Create(parent, id, title, pos, size, style, name);
    }

    bool Create(wxWindow *parent, wxWindowID id = ID_CMAINFRAME, const wxString& title =
        _("CMainFrameDesigner"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(800, 600),
        long style = wxDEFAULT_FRAME_STYLE|0, const wxString &name = wxFrameNameStr);

```

The only way to use a const defined like thet is to create an object from its class.
`CMainFrameDesigner *pMyFrame(.....);`
and then
`pMyFrame->form_size;`

The purpouse of constants generated with the property "generate_const_values" should be an usefull way to instance different objects calling, if needed, static functions like your proposal in [this discussion](https://github.com/KeyWorksRW/wxUiEditor/discussions/841)

I would have expected something like:
```
static const int form_style = wxDEFAULT_FRAME_STYLE;
static const wxPoint form_pos() { return wxDefaultPosition; }
static const wxSize form_size() { return wxSize(800, 600); }
static const wxString form_title() { return wxString::FromUTF8("CMainFrameDesigner"); }
```

The result for the user sould have been like: `MyFooDlg foo_dlg(parent, MyFooDlg::dlg_id, MyFooDlg::dlg_title(),     MyFooDlg::dlg_pos(), ...
`

**Comment by Randalphwa** [comment]
Incoming PR changes the int values to static, and the form_pos and form_size to static functions. I also updated sdi_test to verify that these are accessible outside of a specific instance of the class. It's a reminder to myself that just because a feature compiles, doesn't mean it can be used...

**Comment by rossanoparis** [comment]
Thank you @Randalphwa, but is there something to review, because it generates this [issue](https://github.com/KeyWorksRW/wxUiEditor/issues/1282)
