### ISSUE TITLE
Python font generated code has errors

### ISSUE THREAD

**Issue by gmayo1947** [KeyWorksRW/wxUiEditor#1296]
I create a new project and add a frame and container panel. I now chane the font size from default 9 to say 10. The following sample shows the type of code that is generated:
 panel.SetMinSize(wx.Size(450, 270))wx.FontInfo font_info(10)
        font_info
        panel.SetFont(wxFont(font_info))

I doesn't matter whether this is done from the panel or from a control The only difference is that the "wx.FontInfo font_info(10)" part is now on a separate line. Either way, the code will not run. The view in the Mockup does show the appropriate change(s).

**Comment by KeyWorksRW** [comment]
This was fixed as part of the #1270 bug -- the fontinfo code generation for all three languages was updated.

The next release is currently targeted for 12/11, but if you want to get a fix sooner, you could download one of the daily builds. Just be aware that saving a project with the current daily builds can result in the project file being unreadable in any early released versions of wxUiEditor.

**Comment by gmayo1947** [comment]
I have downloaded the daily build #150 to try and notice that, for python code generation at least, there has has been  a small improvement. However, it has not been fixed entirely.
For instance, just changing the font size on the panel but keeping other default details generates the following:
panel.SetMinSize(wx.Size(450, 270))font_info = wx.FontInfo(10)

The code "font_info = wx.FontInfo(10)" should be on a new line. If the generated file is edited so that change is made, then the form will display. This is OK as a temporary fix but regenerating the code file will obviously overwrite theses changes.

**Comment by KeyWorksRW** [comment]
Two issues: the font_info variable on its own line which has been fixed, and the missing line break after SetMinSize() which still needs to be fixed.

**Comment by KeyWorksRW** [comment]
The additional problems have been fixed and will show up in the next Daily build (152). Thanks for reporting this!
