### ISSUE TITLE
C1001: internal compiler error in src/id_lists.h with VS2019

### ISSUE THREAD

**Issue by Jofagi** [KeyWorksRW/wxUiEditor#1312]
### Description:
I tried compiling main (according to build instructions from readme.md) using VS2019 and I got an internal compiler error for the `id_lists.h` header.
After changing these definitions as follows, the whole thing compiled and linked:

Old: `auto inline LIST_NAME = std::to_array({ /*content*/ });`
New: `constexpr std::array LIST_NAME { /*content*/ };`

**Comment by KeyWorksRW** [comment]
Incoming PR will change "auto inline" to "constexpr auto" which should fix the compiler error. I don't have a way to test against all the versions of the compiler that VS 2019 has released (12 so far), though I'm fairly confident this change should work. Please re-open if you still get an internal compiler error, and I will change the "auto" to "std::array". Thanks for reporting this!

**Comment by Jofagi** [comment]
Sorry, the change you made doesn't do the trick. My guess is that `std::to_array` causes the problem.

**Comment by Randalphwa** [comment]
Okay, I'll turn it into a list. There's other places in the code base that do that, so since you've already been able to compile/link the rest of the codebase, that list should work fine.

**Comment by KeyWorksRW** [comment]
The PR was supposed to mark this as closed, but apparently github got confused by the parenthetical remark between the "Closes" and the issue number. I'll leave it open for now in case the fix causes another problem...

BTW, KeyWorksRW and Randalphwa are two accounts for the same person, and I track notifications for either of them. It doesn't hurt to mention one or the other directly, but I generally get the notification without the direct mention.

**Comment by Jofagi** [comment]
From my point of view, the problem is solved now. Thanks!
