### ISSUE TITLE
Update image file if time-date stamp has changed.

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1338]
### Description:

Now that Nodes can store internal data, it would be useful to store either file size or time/date stamp (or both) for Image files. We want to avoid rereading the entire file every time it is accessed, but it would be useful to check to see if the file has changed since it was last read. Initially this could be added to the Image Lists nodes, but once that's working, it should be added to any node that contains one or more image-type properties.

**Comment by Randalphwa** [comment]
File-date stamp is now part of the `EmbeddedImage` structure, and the time/date stamp is checked (and file reloaded if changed) whenever the code is generated.
