### ISSUE TITLE
Bug: Changing SVG size in form will break the same SVG file in Images List

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1411]
### Description:

When the size of an SVG image is changed in a form, and the SVG image already exists in an Images List but with a different size, the Images List version is no longer generated, and both Images List and Form's path to the image gets changed. The new path doesn't take into account the art directory, so it can be broken by the change.

Expected: size for an SVG should have no effect whatsoever on the embedded structure.

**Comment by Randalphwa** [comment]
Problem was not the size, but rather incorrect lookup of the filename.
