### ISSUE TITLE
Support wxMenuBar forced size which becomes DPI-aware

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1423]
### Description:

Code generation for menus is not DPI-aware. It would be useful if `wxMenuBar` had an option to force image size which we could automatically convert to DPI-aware size. We actually already do this ourselves in our `NavPopupMenu` class:

```c++
    auto dpi_size = wxGetFrame().FromDIP(wxSize(16, 16));
    menu_item = sub_menu->Append(id, label);
    menu_item->SetBitmap(bndl_function(dpi_size.x, dpi_size.y));
```

This would also help with wxWidgets `Art` images where menu images can be either 16x16 or 20x20. It would also mean that wxUiEditor menus that are part of the main toolbar would be much more clear on high-resolution displays now that we are switching all artwork to SVG which scales to any resolution.

**Comment by Randalphwa** [comment]
Actually, the code generation is correct. I walked through the wxWidgets code in the debugger and verified that it scales the bitmap as needed based on the DPI of the display. The internal wxUiEditor code doesn't hurt, but technically it isn't necessary.
