### ISSUE TITLE
Bug: Mockup Panel doesn't display ribbon gallery SVG images

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#1435]
### Description:

The mockup panel is not displaying svg images in a ribbon gallery correctly. It's just showing the unknown file icon.

**Comment by Randalphwa** [comment]
This probably got fixed in PR #1443 -- leastwise, I'm not seeing a problem in wxUiEditor or sdi in wxUiTesting.
