### ISSUE TITLE
Add missing wxPropertyGridManager events

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1461]
With the current version of wxUI only two events are available for wxPropertyGridManager widget
![image](https://github.com/KeyWorksRW/wxUiEditor/assets/33904565/01b5da5b-9f91-429b-984c-fba9f5741313)

Could it be possible to add even the others?

**Comment by KeyWorksRW** [comment]
https://docs.wxwidgets.org/3.2.0/classwx_property_grid_event.html lists the events and descriptions as a starting point. I don't _think_ there are any new ones for wxWidgets 3.3, but that should be checked.

**Comment by Randalphwa** [comment]
C++ events added for both wxPropertyGrid and wxPropertyGridManager. wxPython doesn't support some of these events, so that will need additional work. wxRuby3 needs to wait until I can get a working version again.

**Comment by Randalphwa** [comment]
There was a bug in Ruby code generation that prevented verifying that propertygrid events were being correctly generated for wxRuby3. That has been fixed with the correct code checked into wxUiTesting.
