### ISSUE TITLE
Bug: Images list filename not being used for generated #include statement

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/wxUiEditor#1475]
### Description:

It looks like the filename for the Images list is not being used for the #include generated in any C++ header files that use functions/data from the Images list file. This is currently reproduciblle in wxUiTesting/quick/dlg_test.wxui which uses my_images as the filename, but the generated test_dlg.h uses `#include "images.h"`.

**Comment by Randalphwa** [comment]
I just tried to reproduce this and it worked fine. I have made some changes to image list handling since the bug was created, so I'm going to assume it got fixed.
