### ISSUE TITLE
Bug: The latest daily build doesn't start using Windows 11

### ISSUE THREAD

**Issue by rossanoparis** [KeyWorksRW/wxUiEditor#1483]
### Description:

Just for your information ...

I've noticed that since the last month, more or less, the daily build for MSW doesn't start.
Here below the crash event details I get from MSW Event viewer app.
[crash-event-details.txt](https://github.com/user-attachments/files/16374315/crash-event-details.txt)

Microsoft Windows 11 Pro	
Version 10.0.22631 Build 22631

**Comment by KeyWorksRW** [comment]
Thanks for the report -- while I normally build release versions, they are an internal version, so it's most likely something missing in the non-internal release builds.

In the meantime, the latest update of Windows 11 is claiming the daily zip file itself contains a virus so I can't even download it. That's likely a bug in Microsoft Defender, which also locked me out of quite a few other unrelated zip files -- that and if it really is a virus, it means that the github MSVC compiler is infected...

**Comment by KeyWorksRW** [comment]
I built a release version with symbols so I could debug it, but that version runs fine. I've temporarily switched the daily builds to use the symbol version. It doubles the executable size, but at least it provides a working version while I try to figure out why the github build fails to run, and the exact same build on a local machine runs just fine.
