### ISSUE TITLE
Bug: crash(segfault) when trying to create or rename a wxFrame other than default-name

### ISSUE THREAD

**Issue by PasstScho** [KeyWorksRW/wxUiEditor#1519]
Using:
wxUiEditor 1.2.1.0 on Debian12 (same happens in todays "main" branch 1.2.9.0)
Python 3.11.2
wxPython Version: 4.2.2
(this did not happen to me when using the windows version, even in Wine)

### Description:

wxUiEditor crashes when trying to create or rename wxFrame with other than default-name

Steps to reproduce:
- Created a new project (C++ or Python doesn't matter)
- add a wxFrame
- change name to "Test" or anything
- press ok
- program crashes

### Workaround:
I manually add/change class_name="Whatever" in the .wxui file

### Debug output:
(wxUiEditor:73581): GLib-GObject-WARNING **: 22:53:26.848: invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem'

(wxUiEditor:73581): Gtk-CRITICAL **: 22:53:26.848: gtk_image_menu_item_set_image: assertion 'GTK_IS_IMAGE_MENU_ITEM (image_menu_item)' failed

(wxUiEditor:73581): GLib-GObject-WARNING **: 22:53:48.939: invalid cast from 'GtkCheckButton' to 'GtkLabel'

(wxUiEditor:73581): Gtk-CRITICAL **: 22:53:48.939: gtk_label_set_mnemonic_widget: assertion 'GTK_IS_LABEL (label)' failed
Unhandled standard exception of type "St13runtime_error" with message "locale::facet::_S_create_c_locale name not valid"; terminating the application.

in wxWidgets/src/gtk/window.cpp
![grafik](https://github.com/user-attachments/assets/51a4035e-b179-4d5f-a722-73e3ffbceff5)

![grafik](https://github.com/user-attachments/assets/2035407d-852c-4efb-a7fc-8321a7bdcaf3)

**Comment by PasstScho** [comment]
Btw:
I get a lot of these invalid cast from 'GtkMenuItem' to 'GtkImageMenuItem' Debug messages even at the start of the program so I think they are not related but the second might be, which only appears once when trying to create or rename the frame

(wxUiEditor:73581): GLib-GObject-WARNING **: 22:53:48.939: invalid cast from 'GtkCheckButton' to 'GtkLabel'

(wxUiEditor:73581): Gtk-CRITICAL **: 22:53:48.939: gtk_label_set_mnemonic_widget: assertion 'GTK_IS_LABEL (label)' failed
Unhandled standard exception of type "St13runtime_error" with message "locale::facet::_S_create_c_locale name not valid"; terminating the application.

**Comment by KeyWorksRW** [comment]
I can't repro on Windows, so yes, it does appear to be the `gtk_label_set_mnemonic_widget`. However, I suspect the underlying issue is the use of images in the menus -- that should be handled by wxWidgets itself, but the assertions and crash all appear to be related to that.

**Comment by KeyWorksRW** [comment]
BTW, if you enter the name you want in the initial Dialog that comes up when you create a new wxFrame, does it still crash?

**Comment by PasstScho** [comment]
Luckily with just some more debugging I've found the actual bug.
The line(s) in "tt_string.cpp" called via "CreateBaseFilename" and "filename.MakeLower()":
`auto utf8locale = std::locale("en_US.utf8");`
Reference says "runtime_error is thrown if std_name is not a valid C-locale name." and this is what we've seen -> "locale::facet::_S_create_c_locale name not valid".

My system has:
```
locale -a
C
C.utf8
de_DE.utf8
POSIX
```

I don't have "en_US.utf8" installed and my system is set to German Language. 
It works when I change the string to "de_DE.utf8" or "C.utf8". So here we got the problem. 
I guess wxUiEditor should also work on systems that don't use en_US. I don't know much about locales but maybe change it to a universal locale and try/catch possible exceptions?

**Comment by KeyWorksRW** [comment]
That code was written long before wxString could be built as UTF8. Given how infrequently the tt_string case conversion is called, it makes more sense now to just hand it to wxString and let wxWidgets perform the case conversion. This should take care of the crash. For now I just changed the tt_string call to convert to wxString, perform the conversion, and convert back.

I think the fix got in before the 10/18 daily build.

**Comment by Randalphwa** [comment]
All MakeLower() calls currently use tt_string which in turn has wxString do the actual conversion that avoids the original bug in tt_string.
