### ISSUE TITLE
Bug: wrong code related to class_access changes

### ISSUE THREAD

**Issue by PasstScho** [KeyWorksRW/wxUiEditor#1521]
Using:
wxUiEditor main branch 1.2.9.0 on Debian12 (but I think the same applies for 1.2.1.0 release version)
Python 3.11.2
wxPython Version: 4.2.2

### Description:

Editor produces wrong Python and C++ code (maybe more langs).

Steps to reproduce:
- Create a new python project
- add a new wxPanel
- add a panel (container) to the created Panel
- add a wxStaticBoxSizer to the created container Panel
- see python code "panel" with and "_panel" without underscore
![grafik](https://github.com/user-attachments/assets/e4066d0f-9d82-4d38-a58a-2d0c5483e906)
- click on "_panel"
- change class_access to "protected"
- see python code where underscore disappears but "self." is missing 
![grafik](https://github.com/user-attachments/assets/f3efad01-a4e8-4f61-86d9-93879c5a0329)
(similar problem applies for C++ code... didn't check others)

Added the project file, just in case...
[Empty Project.zip](https://github.com/user-attachments/files/17423733/Empty.Project.zip)

I start feeling bad for posting so many bugreports ;-)

**Comment by KeyWorksRW** [comment]
I do have an entire repository of UI elements designed to provide coverage for all generated languages, but it is impossible to cover all scenarios. While I am disappointed that there are still bugs that I haven't found yet, I'm actually delighted that someone is finding them -- and providing very useful bug reports! So please, keep reporting any problems you find.

**Comment by KeyWorksRW** [comment]
I have this fixed, but the fix could potentially affect other code generation, so I'll need to spend some more time verifying that I didn't just break code generation somewhere else. It should be in the daily builds within a couple of days.

**Comment by PasstScho** [comment]
awesome - this works for my projects!
Thanks your for your great & quick work!
