### ISSUE TITLE
Bug: Release build is not changing from XPM to Header images correctly

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/wxUiEditor#192]
### Description:

The release build of **wxUiEditor** is messing up the `size` sub-property of Header bitmaps -- we're getting a `[16;-1]` for size when changing from an XPM image to a Header image. I'm using the Release build to make the changes to the mainframe menu and toolbar so that I can compile and test the changes in the Debug build -- but that process is currently broken, requiring hand-editing the project file.

**Comment by KeyWorksRW** [comment]
The entire Header image type has been removed (from the UI) so this is no longer an issue.
