### ISSUE TITLE
Bug: BookPage gets a parent sizer without borders or flag properties

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#202]
### Description:

The parent sizer for a form should not have a border or size. However, we're also ending up with "parent" sizers underneath book pages -- and those definitely _do_ need the properties that allow for expansion, proportion, borders, etc.

**Comment by Randalphwa** [comment]
The `Layout` property category is used to affect how a parent sizer is supposed to add the current node. The sizer itself doesn't actually have any settings affected by this category. As such, the only time a sizer should have a `Layout` category is if it has a sizer parent -- which is not the case for book pages.
