### ISSUE TITLE
wxMenu as a form child doesn't do anything useful, but does generate a memory leak

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#211]
### Description:

All forms are allowed to create a **wxMenu**, but we simply create the menu on the heap and don't do anything with it. **wxFormBuilder** creates a menu in the form's ctor and hooks it up to a mouse right-click event. If we don't support **wxMenu** as a form child, then we need to warn the user if they import a **wxFB** project that uses it.

If we do support it, then it should be added as a `std::unique_ptr` so that it will be automatically destroyed in the classes dtor rather than creating a class destructor just to delete it. We would also need to fill in the `wxEVT_RIGHT_DOWN` event for the form with a lambda that displays the popup menu. That allows the user to override it if needed -- or at least to see that the event is already in use.

**Comment by KeyWorksRW** [comment]
Currently we have taken **wxFormBuilder**'s approach to menus in a base class. In the base class destructor, the menu is always created on the stack and then deleted in the destructor. While that does work, it's a sloppy coding technique since those menus always get created even if they are never used.

I think a better atlernative would to be to create a special menu widget that asks the user to specify the name of the function for this specific menu. That function would be created as a class `protected:` class method. The code generation for this function would create a method that creates the menu on the stack and calls PopupMenu(). If the user specifies a wxEVT_CONTEXT_MENU for the base class form and popups the edit dialog, we could auto-fill in the lambda function with the name of the menu functon.

The downside to this method is that the derived class can't modify the menu before it displays, and menu items can't have member variable names.

**Comment by Randalphwa** [comment]
PR #268 removed the ability to add `wxMenu` as a child. PR #273 adds a `wxContextMenuEvent` generator. This is probably roughly what **wxFormBuilder** intended, with the difference being that `wxContextMenuEvent` only generates the popup menu if a wxEVT_CONTEXT_MENU is actually generated, and it only works for forms.
