### ISSUE TITLE
Bug: Mockup changing to first page when panel added to a page

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#224]
### Description:

When you add a panel to a ribbon page, mockup doesn't re-display the page that the panel was added to, instead displaying the first page.

**Comment by Randalphwa** [comment]
I can't reproduce this now -- I did a bunch of work on selection handling a few months back, so apparently this got fixed in the process. If it re-occurs, I'll need repro steps.
