### ISSUE TITLE
Change dialog constructor

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#245]
### Description:

Currently, a dialog's constructor includes all the parameters that get passed to the **wxDialog** constructor. That doesn't really make a lot of sense given that all of those parameters will have been set in the properties for the dialog. Almost all of the time an instance of the dialog will be created supplying only the parent window. Once the dialog is created, but before it is shown, any of the properties passed to **wxDialog** can be overridden by calling individual methods such as **SetTitle()** or **SetId()**. It doesn't make sense to me to always pass 6 parameters to the constructor when only one is actually needed.

The other thing to keep in mind is that using the paramater version of the **wxDialog** constructor means an instance of our base class will pass 6 parameters to our constructor, which will pass 6 parameters to the **wxDialog** constructor which will then pass 6 parameters to the `wxDialog::Create()` function. If instead we just required the parent window for our constructor, then we could call the empty `wxDialog()` constructor and call `Create()` as the first line of the constructor code:

```c++
MyDialogBase::MyDialogBase(wxWindow* parent) : wxDialog()
{
    Create(parent, ...);
```

Aside from the parent, all additional parameters would be passed in based on the properties the user set. Assuming a dialog that has wxRESIZE_BORDER set, here's the before:

```c++
// Header file
class MyDialogBase : public wxDialog
{
public:
    MyDialogBase(wxWindow* parent, wxWindowID id = wxID_ANY,
        const wxString& title = wxString::FromUTF8("My Title"),
        const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxDefaultSize,
        long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
};

// Source file
MyDialogBase::MyDialogBase(wxWindow* parent, wxWindowID id, const wxString& title,
		const wxPoint& pos, const wxSize& size, long style) :
	wxDialog(parent, id, title, pos, size, style)
{
```

If we just require a parent parameter, the generated code would look like this:

```c++
// Header file
class MyDialogBase : public wxDialog
{
public:
    MyDialogBase(wxWindow* parent);
};

// Source file
MyDialogBase::MyDialogBase(wxWindow* parent) : wxDialog()
{
    Create(parent, wxID_ANY, wxString::FromUTF8("My Title"), wxDefaultPosition, wxDefaultSize,
        wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER);
```

In the case where the dialog instance needs a different title the old code would be:

```c++
    MyDialog dlg(this, wxID_ANY, _("My New Title"));
    dlg.ShowModal();
```

The new version would be:

```c++
    MyDialog dlg(this);
    dlg.SetTitle(_("My New Title"));
    dlg.ShowModal();
```

The new method avoids having to specify an id, and arguably makes the code more readable.

**Comment by Randalphwa** [comment]
It's worth noting that while the current code generator will pass in the correct size as part of the constructor, it doesn't actually work because any call to `SetSizerAndFit()` will override this value. The latest commit now calls `SetSize()` after the `SetSizerAndFit()` call which correctly sets the dialog size. Bottom line is that specifying the size in the constructor is useless.
