### ISSUE TITLE
Check for prop_size should be in Property panel, not Mockup panel.

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#259]
### Description:

The Mockup Panel has code that id Debug builds will display a warning if the user specified a `prop_size` that is not within what was set for a minimum or maximum size. That's a valid warning, but the check  belongs in the Property Panel -- i.e., the check should be made when the user sets the `prop_size` value. It should _not_ be in the Mockup panel.

**Comment by Randalphwa** [comment]
#260 removed the check in Mockup -- so this is now a feature request, not a design change.
