### ISSUE TITLE
Add ttLib back as a submodule

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#306]
### Description:

I thought ttLib wasn't going to be changing very much any more, but alas wtih C++20 breaking some C++17 features (u8path() and u8string() in std::filesystem), there are going to be changes we need to pick up. We could of course just copy them, but it would be safer just to go back to having a submodule. The part that needs to remain is building directly rather than building the library -- that's going to make builds a lot easier later on when we add cross-platform building, as well as hooking up automated builds on github.

**Comment by Randalphwa** [comment]
Most of the changes needed to **ttLib** are being driven by the work being done on **wxUiEditor**. I'd rather work out those changes in here first, and then merge them into the **ttLib** repository as needed. It also avoids the whole syncing of sub-modules headache...
