### ISSUE TITLE
Should art provider images support a fallback image?

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#31]
### Description:

XRC files allow for a fallback image to be used if an art provider bitmap fails to load. That could be useful if people use GTK art and want to fallback to a different image on Windows or Mac.

**Comment by Randalphwa** [comment]
I think most people are going to use the standard Art files, or they are going to use the GTK art files knowing that their program is designed for Unix only. Expanding the Art property to include this not only complicates our own code, but also complicates it for the majority of users who won't use it.
