### ISSUE TITLE
Find cause of Navigation Panel not displaying node deletions

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#326]
### Description:

The navigation panel is not working well when items are moved or in some cases, simply changed. The problem can be severe enough to cause a crash. A thorough code review of the Navigation Panel code is needed to find why removing nodes is causing so many problems.

**Comment by Randalphwa** [comment]
This appears to be fixed, likely as a result of PR #336 or one of the other PR's between 335 through 338. Reopen if it shows up again.
