### ISSUE TITLE
Add a project-specific flag that prevents saving the project

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#385]
### Description:

It's possible to load a project file from a newer version of wxUiEditor that has properties that we don't recognize. It's likely that the various objects will display just fine, but if the project file is saved then those properties will be lost. What we need is a flag for a project that disables Save. That way a project can be loaded, but the user has to use SaveAs if they want to save the project.

**Comment by KeyWorksRW** [comment]
Argh, this should have been prioritized for the 1.0 release since there are going to be quite a few additions to the project file in 1.1, and if the user loads a 1.1 project file with a 1.0 version of wxUiEditor (ignoring the warning that wxUiEditor will display not to do that) and then saves the project, then it could eliminate a lot of settings for code generation in the new languages.

Bottom line, let's prioritize this for the 1.1 release so that we don't run into the issue again in future releases.

**Comment by KeyWorksRW** [comment]
Hmm, the more I think about this, the more I think it will just create confusion. The user will have already been warned about the project file potentially being unsupported. The Save button will be disabled unless the user makes a change. So we probably shouldn't disable it, though I suppose we could display a warning about saving it over an older version.

**Comment by Randalphwa** [comment]
I don't think this is useful enough to add to the UI (which already has a _lot_ of options). If the project file is tracked, then restoring it is straightforward, and if it's not tracked it's probably not being shared between developers.
