### ISSUE TITLE
Add support for wxMDIChildFrame

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#393]
### Description:

It would make sense to add support for a **wxMDIChildFrame** -- it's essentially the same as a regular **wxFrame** -- it just requires the caller to use a different parent. Note that **wxGlade** supports this, so if we add it as a form, then we should also support importing it from **wxGlade**.

**Comment by Randalphwa** [comment]
There's only one wxGlade project file on github that uses wxMDIChildFrame -- and it only has it in the project, it apparently does not use the generated code.

Looking at the wxWidgets wxDocView sample, I don't see how creating this window would be useful. For a View, you'll simply create a single control or a panel -- and we already support a stand-alone panel as a class. I just don't see this being used by anyone.
