### ISSUE TITLE
Change Convert dialog and h_img output files

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#409]
### Description:

If we use `inline` instead of `inline constexpr` I think it will still work with pre-C++17 compilers, they just won't make the variable unique. We should confirm that, and if so, remove the C++17 option from the Embed dialog and always prefix with inline.

The Embed dialog should have an option to include the `GetImageFromArray()` function that we use for embedded images. Since it's prefixed with `inline` it's fine to put it in a header file that's included in more than one place. The one caveat is that it should be in the wxue_img namespace to avoid conflict -- which also means the generated class constructors also need it in their namespace section.

If the array is also within the `wxue_img` namespace then the header file can be used interchangeably with the `Embed` command as long as the original art doesn't change. For a C++17 compiler this will automatically prevent duplicates.

**Comment by Randalphwa** [comment]
The convert dialog has been removed (except in Debug builds) and support for h_img as an output format has been removed. As such, this issue is no longer relevant.
