### ISSUE TITLE
Bug: wxSimpleHtmlListBox defaults to 0 by 0 dimension (invisible)

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#42]
### Description:

The **wxSimpleHtmlListBox** won't show up by default unless both the expand flag is set and proportion is set to at least 1. The other option is to set the minimum size. Without anything telling the box to expand, it will be invisible because it takes up no space.

**Comment by Randalphwa** [comment]
This isn't the only control that needs expand and/or proportion set to get a reasonable size. We need a general purpose solution which can then be applied individually as needed.
