### ISSUE TITLE
Convert Image needs to accept wxFormBuilder-generated image header files

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#425]
### Description:

The `Convert Image` dialog needs to be able to convert from formbuilder and other header files into our own `.h_img` format. We've already got code for reading the formbuilder version, so it's just a matter of hooking it up to the input.

Added to Alpha milestone since this may impact people importing and modifying an existing **wxFormBuilder** project.

**Comment by Randalphwa** [comment]
This was already in place -- it got disabled when we switched from .h to .h_img for the input extension. We now accept either input format, which once again allows us to load wxFormBuilder header array files. This was changed in the PR that removed the c++17 checkbox.
