### ISSUE TITLE
Bug: dataViewListColumn image is a placeholder

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#446]
### Description:

The image for dataViewListColumn is set to a placeholder (doc_mdi_frame) -- and dataViewColumn is using dataviewlist_column.png.

**Comment by Randalphwa** [comment]
Both dataViewListColumn and dataViewColumn use the same image -- which I think is fine since neither can have the same parent, and they both are used to add a text column to the parent control.
