### ISSUE TITLE
Add an Image "form" with Embed children

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#452]
### Description:

The advantage of using an Embed image instead of a Header image is that it will automatically be updated if the original art is changed. However, that requires the image to be used somewhere in the UI.

Another option would be to create an Image category for the Forms panel, and create a **Images** form that accepts **Embed** children. Each **Embed** child would be a node that specified an Embed image which would work the same as if it was added to a UI element.

If this _form_ was forced to be the first form of a project, then it would always get first crack at creating the actual character arrays. Adding a command that adds all UI images would mean a single header file would give the user access to all embedded images along with the function to convert them into an actual wxImage.

Note that this is related to #438 in that it would allow us to eliminate the last 12 header files we currently need. It would also simplify our code by only needing to include a single header file instead of the 9 we currently need to include.

**Comment by Randalphwa** [comment]
The implementation does not require the `Images` file to be first -- the code that checks for when a node first appears _always_ switches the node to the `Images` file if the image is located in that node.
