### ISSUE TITLE
Change original_art property so that it supports multiple directories

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#533]
### Description:

For original projects, it's likely that all art work will be in a single directory. However, importing Windows Resource files may use multiple locations for the resource files as well as multiple locations for the artwork. It would be helpful if the original_art property supported multiple directories.

Note that the main advantage of using original_art is that all image files can then be specified just by name, which means changing their actual location only requires changing one property instead of changing every single reference to the image.

**Comment by Randalphwa** [comment]
I looked into this while working on #532 and it's not going to work. There's too many places where we need to display a dialog to request a filename or a directory -- and the OS only supports one directory for that. Other complications are the auto-complete for image names, the limitation of the path name to valid characters (which means the user can't enter an invalid character to use as a separator). The final problem is that it would be unexpected behavior -- users are used to looking for a file in one directory at a time, not have multiple directories.
