### ISSUE TITLE
Bug: Invalid parent when adding wxStyledText

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#57]
### Description:

I don't know if this is specific to the **wxStyledText** control, or a problem in general, but when I had a checkbox highlighted, and added a **wxStyledText** control, it became a child of the checkbox instead of a child of the parent sizer.

**Comment by Randalphwa** [comment]
I can't reproduce this. Given that the bug was entered 6 months ago, it doesn't surprise me that it now works correctly given the amount of work I've done on the code generation.
