### ISSUE TITLE
Bug: Derived file's #include incorrect if derived and base files are in sibling directories

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#577]
### Description:

If the base file is set to be in one directory, and the derived file is set to be in a sibling directory, the derived file will not specify the correct location of the generated file's header file. That file needs to be converted to a relative location from the derived file's location.

**Comment by Randalphwa** [comment]
Odd, I could have sworn I saw this happening, but I just tested it and it worked fine. Need a repro case...
