### ISSUE TITLE
Handle failing to open a project better

### ISSUE THREAD

**Issue by PBfordev** [KeyWorksRW/wxUiEditor#601]
Creating an empty project after failing to open existing one leaves the editor in an invalid state.

How to reproduce.
1. Launch the editor and from the start screen under "Open recent project" choose a project that does not exist (anymore).
2. In the message box complaining that the project could not be loaded chose "Yes" to create an empty project.
3. The editor is launched but there is no root item (Project) in the left window.
4. Attempting to use the editor leads to the program hanging. Creating a new empty project creates an empty project with a root but for example adding controls makes them disabled in the left window.

**Comment by KeyWorksRW** [comment]
This should get tied into #608. The splash screen either shouldn't display non-existent projects at all, or it should _not_ go away if the user tries to open a project that no longer exists.

LoadProject() will have created a new m_pjtSettings whether loading the project succeeds or not. That gets deleted and recreated the next time LoadProject() is called, but if it fails and the user wants an empty project, then LoadProject() isn't called and m_pjtSettings is bogus (m_project is probably fine, but that should be checked as well).

Technically, it's not a crash, but might as well be if it's hanging -- marking as such to up the priority.
