### ISSUE TITLE
Bug: Left-over code from previously opened project

### ISSUE THREAD

**Issue by PBfordev** [KeyWorksRW/wxUiEditor#604]
When there was an open project with some code generated, creating a new empty project keeps the code from it.

How to reproduce:
1. Have a non-empty project opened, with code generated displayed.
2. Create a new empty project.
3. The code from the previous project is still there in the code tab that was displayed (source or header), it is cleaned from the other one.

**Comment by KeyWorksRW** [comment]
BasePanel::GenerateBaseClass() needs to clear the display if there is no form to display rather than just returning.
