### ISSUE TITLE
Move and enhance the class_decoration property

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#606]
### Description:

The `class_decoration` property of a form needs two changes. First, it needs to be moved below the derived class properties. Secondly, it needs to be applied to the Derived class _only_ if one is specified, and applied to the base class if not.

**Comment by Randalphwa** [comment]
The location of the property has already been moved. I'm dubious about trying to outguess the user and know whether they want the decoration only for the base class, only for the derived class, or both. I think we should leave this up to the user to decide.
