### ISSUE TITLE
Add font, foreground and background coloring customization for code display panels

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#620]
### Description:

The font and coloring of code is highly personal. If we add a sizer above the scintilla control, we could add a font button, followed by a combo box indicating what type of coloring we support (text, comments, keywords, numbers, etc.) followed by a foreground and background button. These would all be saved off to config so that once set, it would always be displayed that way.

**Comment by Randalphwa** [comment]
The font for all panels can be set in the General tab of preferences, and each language tab allows overriding various colors.
