### ISSUE TITLE
Support wxStaticText label markup on Windows

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#621]
### Description:

We now have the ability to switch to the generic version of a control if needed. One situation where this could be useful is if the user wants to use label markups for static text. The native version doesn't support this under Windows, but the generic version does. We could check for styles, and if the user has not specified a border or other Window style that doesn't display correctly in the generic version of Windows, then we could simply create the generic version which should work on all platforms.

**Comment by Randalphwa** [comment]
Unfortunately, this won't work. Once you include <wx/generic/stattextg.h> you can no longer use the regular **wxStaticText**. That's because stattextg.h has the following:

```c++
#define wxNO_PORT_STATTEXT_INCLUDE
#include "wx/stattext.h"
#undef wxNO_PORT_STATTEXT_INCLUDE
```

#defining wxNO_PORT_STATTEXT_INCLUDE means that none of the platform-specific wxStaticText implementations get pulled in.
