### ISSUE TITLE
Improve Insert Widgets dialog

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#653]
### Description:

The "Insert Widget" dialog is useful when you have no idea which of the ribbon panel pages contains what you are looking for. There are some changes that might make this dialog even more useful.

First off, if there is nothing in the "Name:" field, then list _all_ controls. Currently, having a dialog with everything empty looks really strange, with the initial impressiong being that it is broken. We should probably add a hint text to the Name field that tells people to type here to filter the list below.

Secondly, providing a filter would be useful (probably needs to be persistent). Sample filter list below:

```
    All
    Bars
    Books
    Editors
    Lists
    Pickers
    Sizers
    Text Display
```

**Comment by Randalphwa** [comment]
I'm taking a somewhat different approach to this, and instead listing only the widgets that can be added to the current selection. That's still a big list if a sizer is selected, but it no longer lists anything that can't be added. For non-sizers, the list is going to be fairly short, which would make a filter seem pointless.
