### ISSUE TITLE
Bug: Lambda is wrapping in the middle of a quoted string

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#671]
### Description:

It doesn't happen often, but the lambda code is wrapping in the middle of a quote and the resulting lines can no longer be compiled. This can be seen in the ttCode DlgExcludeBase dialog when the line is pasted in, saved, and reloaded.

**Comment by Randalphwa** [comment]
I can't reproduce this. I suspect that since this issue was created, the styled text control is now set to automatically wrap. Unless **wxUI** wraps the text returned from the event editor (which is shouldn't) this should work fine.
