### ISSUE TITLE
Remove image_size property from Book controls

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#692]
### Description:

All of the books that accept bitmaps for their pages have an image_size property that will scale all bitmaps to that size. The idea was that wxImageList would be created with the correct size, and all bitmaps would be scaled to that size. Or at least that was the plan. In most cases, it didn't actually work correctly because the wrong property was being used to get the size.

Starting with wxWidgets version 3.1.6, `wxImageList` is effectively deprecated in favor of using `wxVector<wxBitmapBundle>`. That means there is no longer an option to specify the bitmap dimensions in the ctor.

The `image_size` property should be removed along with all the scaling code even when generating the older `wxImageList` code. This requires the user to supply images that all have the same size, which will then continue to work correctly if they build with wxWidgets 3.1.6 or later.

**Comment by Randalphwa** [comment]
Note that wxFormBuilder has a `bitmapsize` property for books, however it doesn't scale the images, so if they are the wrong size, they won't be loaded.

A more reliable approach that we could use is to use the dimensions of the first bitmap loaded to set the wxImageList size. As long as all the images are the same size, this will work fine, and doesn't require the user to know ahead of time what the dimensions of the bitmap is.

When wxBitmapBundle is used, the images don't have to be the same size. You can see this working in the wxUiTesting app for a treebook -- the sub pages have a smaller image size then the outer pages. They fail if using wxImageList without scaling them, and work find when wxBitmapBundle is used.

**Comment by Randalphwa** [comment]
Scaling has been removed from images. The `image_size` property has been changed to `Size` and is only used for SVG images. For all other images, it will display the image's size, but not allow the user to test it.
