### ISSUE TITLE
Remove prop_display_images from books

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#733]
### Description:

The various books that can contain images have a `display_images` property that controls whether or not images our displayed. wxUE uses that to determine whether or not to generate an image list for the book. It's a bit odd, though, for a page to specify a bitmap which then doesn't show up because the dev needs to know to turn it on in the book property.

I think we should remove this property, and instead rely completely on whether any of the pages specify a bitmap -- if they do, we create an image list and display the bitmap.

**Comment by Randalphwa** [comment]
I think it's worth keeping the property in the off chance that someone wants to turn off all image display without having to remove every page's image. However, the default should be on. Code generation and Mockup already correctly deal with a situation where none of the pages have images, so defaulting to on won't break any books without images.
