### ISSUE TITLE
Bug: Can't pass default GUI font to XRC handlers

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#739]
### Description:

Passing the default GUI font to the FontPickerGenerator is not working correctly. On Windows 10, this is showing up as Arial instead of Segoe UI. This will require updating GenXrcFont() in gen_xrc_utils.cpp.

**Comment by KeyWorksRW** [comment]
wxLua and wxPHP were dropped, and we don't need this for wxPython.

Triaging this to a 1.x release -- needs to be fixed, but not enough to hold up the 1.1 release.

**Comment by Randalphwa** [comment]
I just checked this, and it appears to be working fine. Closing unless it shows up again...
