### ISSUE TITLE
Add disabled property to toolbar tools

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#748]
### Description:

wxAuiToolBar, wxToolBar, and wxRibbonBar all have a `EnableTool()` function -- we need to add a property to support this.

**Comment by Randalphwa** [comment]
wxRibbonBar will need to be handled differently because it doesn't support using wxID_ANY to generate a unique id, and the return class pointer from AddTool() cannot be used (it's a forwarded class with no header containing the declaration).
