### ISSUE TITLE
For internal/debug add a C++ preview using CreateMockup calls

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#749]
### Description:

Displaying a wxDialog or wxFrame using XRC is quite valuable for determining if our XRC generation is correct. Given that most of our generators support CreateMockup, it seems like it would be useful in internal/debug builds to also generate a wxDialog or wxFrame using the Mockup code. The main advantage is that our Mockup panel does a poor emulation of wxDialog and wxFrame -- so there are times when the actual dialog or frame doesn't work as expected.

**Comment by Randalphwa** [comment]
This is up and running for dialogs, and more importantly it also supports side-by-side comparison of C++ generated UI and XRC generated UI. I'll add more functionality to it as the need arises.
