### ISSUE TITLE
Need to fully implement an image component to use for image lists

### ISSUE THREAD

**Issue by ghost** [KeyWorksRW/wxUiEditor#78]
### Description:

The **wxToolbook** will require a **wxImageList**, and there are other controls that would definitely benefit from it. We do have a "image" node type declared, but no compinfo class any more. We need to recreate this component and allow it as unlimited children for components that need multiple images. We can then have the parent component generator parse those children and create an image list from them.

**Comment by KeyWorksRW** [comment]
Adding this to the 1.1 milestone because this needs to be checked out to see if it's needed for the new python, lua and php code generation.

**Comment by KeyWorksRW** [comment]
Not needed for wxPython, and the other languages were dropped. Postponed to a 1.x release.

**Comment by KeyWorksRW** [comment]
wxToolBook supports a bundle_list for multiple images. I think the current code generation for all three languages now generated image lists as needed.
