### ISSUE TITLE
Add platform-specific support

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#810]
### Description:

Sometimes a user is only going to want a control to show up on a specific platform. XRC supports this with a `platform=` attribute for the object. We could support this by adding a `prop_platform` bitlist (which would default to `all`). C++ code generation would add `#if defined()` around control construction and it's settings.

If we exposed our C++ preview dialog (currently this is Internal only), then we could add a Preview menu which would have checkable menu items for the three platforms (defaulting to all) and a preview command for C++ and XRC (and maybe the C++/XRC comparison dialog).

**Comment by Randalphwa** [comment]
The XRC preview is going to use the current platform's library to choose whether a control should be displayed or not. Since the UI isn't going to look like a different platform anyway, it makes more sense to just update the C++ Preview code so that it honors platform specific controls.
