### ISSUE TITLE
It would be usefull to organize items using folders

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#823]
### Discussed in https://github.com/KeyWorksRW/wxUiEditor/discussions/820

<div type='discussions-op-text'>

<sup>Originally posted by **hobbitdev** November 12, 2022</sup>
Hi at all

In case of a huge wxUiEditor project, it would be usefull to organize items using nested folders, like the picture below.
Nothing special, only a normal way to keep the project tidy up.
What do you think about it, could it be accepted as a new feature to introduce starting from the new release ?

![image](https://user-images.githubusercontent.com/33904565/148948781-32b2cd23-11e2-47ae-83d9-a2adc4c8214d.png)

Best regards
Rossano
</div>

**Comment by hobbitdev** [comment]
Thank you @KeyWorksRW 

Some projects can reach big dimensions in elements
![image](https://user-images.githubusercontent.com/33904565/201515592-dfdce2b5-eda8-4591-8c32-3215e860806a.png)

Regards
Rossano
