### ISSUE TITLE
Remove support for wxPHP

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#840]
### Description:

The most recent binary available for wxPHP is 3.0.2 built on PHP 5.6.9 and wxWidgets 3.0.x. For 5 years now there has been a request to at least upgrade to PHP 7.x, though no mention of upgrading to a newer wxWidgets version. That work is still not completed, and there's no mention of supporting more recent versions of PHP (8x.). The dev for wxPHP has stated he has very little time -- only 9 commits in the last almost 3 years would certainly confirm that.

wxPython is already built on wxWidgets 3.2, and while I don't have a binary yet, wxLua supports wxWidgets 3.2 as well. That means in terms of generating code, I only have one version of wxWidgets to support. Adding a bunch of conditional code to support a 10-year old version of wxWidgets is both a lot more work, but also makes the code base harder to read and maintain.

Since a lot of the outer controlling code is already in place to generate wxPHP code, I think it makes sense to leave it just in case at some point in the future a dev is able to update wxPHP to something more current. However, the UI (panel and properties) should be dropped, the code for wxPHP in the actual widgets should be removed, and no further work should be done on wxPHP.

**Comment by Randalphwa** [comment]
wxPHP is closer to C++ code then it is to wxPython and wxLua. Ironically, it takes a lot more code to generate, since most of the
C++ code generation has it's own function(s). As a result, removing wxPHP support cleans up/optimizes some of the code and also allows elimination of a few of the low level functions.
