### ISSUE TITLE
Output const/static functions for parameters in form header files

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#844]
### Discussed in https://github.com/KeyWorksRW/wxUiEditor/discussions/841
 
As per the discussion, the idea is to provide something in the base class header file that can be used to represent each parameter. The goal is so that you can override a parameter in separate instances of the form without requiring finding and re-implementing each parameter before the one that needs changing. For example, if the only thing changing in a wxDialog is the window name, you have to provide 5 parameters before you can specify the different window name. See end of discussion for an example of how this could be implemented.

**Comment by KeyWorksRW** [comment]
Much as I'm reluctant to add yet another C++ property (there's already 10), there should be a way to disable it. Adding the property defaulting to true will mean the functionality is discoverable by those who really need it, and those who really don't want the extra 5+ lines in the generated header file can simply uncheck the property (if they can find it <g>).

**Comment by hobbitdev** [comment]
I understand your comment, if I were you, I wouldn't be afraid of options.
The more your RAD tool will be flexible, refferring to generated code, the more it will be appreciated by developers.
As I see it a RAD tool shouldn't force developers to adapt using its way to generate code, on the countrary a RAD tool should be as mach as flexible and versatile as possible.
