### ISSUE TITLE
Bug: Inserting a wxAuiToolBar bar, the wrong wx header file is added

### ISSUE THREAD

**Issue by hobbitdev** [KeyWorksRW/wxUiEditor#850]
### Description:
Perhaps I'm missing something, but as I tried to insert a wxAuiToolBar I would have expected `#include <wx/aui/auibar.h>` instead of `#include <wx/toolbar.h>` which will lead in a building error
![image](https://user-images.githubusercontent.com/33904565/205138114-72a08b25-eafe-4f41-a5b3-fd78eb0c98a7.png)

**Comment by KeyWorksRW** [comment]
This was fixed in #796 -- however the commit didn't mention the fix to the include file. I've now listed the fix in the CHANGES.md file.
