### ISSUE TITLE
Add additional Paste menu commands to the various navigation context menus

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#86]
### Description:

Currently, the context-menu for a book control does not include the Paste menu. If the current contents of the clipboard contains a BookPage class, then it would be really useful to add that to the menu.

While we're at it, it would make sense to look at some of the other context menu commands and add/remove/disable the Paste menu base on it's current content.

**Comment by Randalphwa** [comment]
Actually, containers already add a Paste menu, but only if the clipboard has something that we can actually paste into a container. For consistency, it would be better to always display the menu, and disable it if there's nothing valid to paste.
