### ISSUE TITLE
Add Preference setting to enable/disable m_ prefix added to class members

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#867]
### Description:

When a widget is declared as needing class access, wxUE adds a `m_` prefix by default. While not a standard for C++, it is a common practice for class members to have this prefix.

In Python, class members are specified with a `self.` prefix, As such, the `m_` prefix is an odd way of specifying a class member. I.e., `self.foo` looks normal, but `self.m_foo` does not.

We could just automatically remove the `m_` prefix when generating Python code, but does contain a risk of having a duplicate variable name. The user can override a variable name to anything they want, even if class access is set to `protected`. That means if the user creates a text control and names it to `m_foo` and creates a second text control and names it `foo` it will _not_ create a conflict error in wxUE since the names are unique. However, if Python automatically removes the `m_` prefix, then the generated code will be invalid.

The safest way to handle this is to add it as a Preference setting. That allows the property grid to ensure that all variable names are unique. That should be fairly straightforward as the `m_` prefix gets added in propgrid_panel.cpp.

**Comment by Randalphwa** [comment]
I'm about to add a PR that will close this. Now that we have a preferred code generation property, we can be a bit smarter about what prefix to use. Only C++ code generation should use the `m_` prefix for class members. Python code generation should use a single `_` for non-class members (referred to as private variables in Python documentation).
