### ISSUE TITLE
Automatically add a sizer when a container widget is created

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#876]
### Description:

Any container is only allowed to have a sizer as the child. For a container like wxCollapsiblePane, it may not be obvious to the user what they should add. Since the user can easily change the sizer type (via the right-click menu), it makes sense to automatically add a sizer whenever a type_container widget is created.

**Comment by Randalphwa** [comment]
wxPanel already adds a sizer automatically. Many of the other _containers_ don't actually need to start with a sizer. Note that wxWidgets does not require anything deriving from **wxWindow** to have the first child be a sizer.
