### ISSUE TITLE
wxTreebook needs to have support for sub-pages.

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#89]
### Description:

Unfortunately, this is not a simple fix. Ideally, we'd use a **BookPage** component that accepts a BookPage child if, and only if, the root parent is a **wxTreebook**. Implementing it will also mean the common code for handling image lists won't work, since we will need a recursive function to step however deep is needed to get all sub-pages, their sub-pages, etc.

**Comment by Randalphwa** [comment]
Adding one sub-level is fairly straightforward. Adding unlimited sub pages is going to complicate the code. My inclination is to support one level of sub page, but not support a nested level below that. I.e.:

```
    wxTreeBook
        Page 1
            Sub Page 1
            Sub Page 2
        Page 2
```

What would not be allowed is adding a page as a child of the sub pages.
