### ISSUE TITLE
Determine whether changing tab height in wxAuiNotebook now works

### ISSUE THREAD

**Issue by KeyWorksRW** [KeyWorksRW/wxUiEditor#936]
### Description:

wxFormBuilder has a `tab_ctrl_height` property for `wxAuiNotebook` which wxUiEditor does not support. As I recall, the last time I tried this, `wxAuiNotebook` didn't change when the height was set, though that testing was done on a pre-3.2 version of wxWidgets. We need to test it again, and if it works we can add the property. If not, we need to ignore it if wxFormBuilder set the value to `-1` (which is it's default) and complain if it's set to a non-default value.

**Comment by Randalphwa** [comment]
Setting the height does work if used after the tabs are created. However, all it does is expand the white-space below the tab -- it doesn't use that additional space for bitmaps or text. I don't see any value to that, so unless there is a specific use request for it, I'm not going to add support for it.
