### ISSUE TITLE
Bug: Two bugs in C++ code generator 

### ISSUE THREAD

**Issue by amreisa** [KeyWorksRW/wxUiEditor#956]
### Description:

I try to make some wxDialog with wxUiEditor, And I got tow C++ code errors from C++ generator with wxGridBagSizer.
##Note
this job done Under winehq And I will try under windows soon.
And here [MyProject_.zip](https://github.com/KeyWorksRW/wxUiEditor/files/11004339/MyProject_.zip) example.
1) open { and don't close it in cpp file in line 72
2) Add . operator in cpp file in line 75 

Thanks for great job.
Best regards
Amr

**Comment by KeyWorksRW** [comment]
Bug confirmed -- it's not related to the platform, so no reason to specifically test on Windows. The bug occurs when processing a `prop_colspan > 1`. Similar code generation is in flex_grid_sizer, so both will need fixing.

**Comment by Randalphwa** [comment]
The problem with the un-closed brace only occurs in wxGridBagSizer, and occurs when either growablecols or growablerows is set. 

The problem with the invalid period after the variable name also only occurs in wxGridBadSizer, and only if the parent is not a form.

Thanks for including the project file -- that made it very easy to track down the source of the problem!
